config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "app#index"
  devise_for :users
  resources :clocks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/clock.rb
class Clock < ApplicationRecord
  include Format
  # Relationships ...............................
  belongs_to :user

  # Enums .......................................
  enum_for :status, %w[running paused stopped]

  # Attributes ..................................
  attribute :duration_time, :string

  # Validations .................................
  validates :description, presence: true
  validates :start_time, presence: true
  validates :status, presence: true, inclusion: { in:  %w[running paused stopped] }

  # Callbacks ..................................
  after_initialize :set_start_time
  after_initialize :set_duration
  after_create :set_end_time
  before_update :set_end_time

  private

  def set_start_time
    self.start_time ||= Time.current
  end

  def set_end_time
    return if status == "running"
    self.end_time = start_time + duration.seconds
    self.duration = format_to_seconds(duration_time)
    save
  end

  def set_duration
    if duration.positive?
      self.duration_time = seconds_to_format(duration)
    elsif status == "running"
      self.duration_time = seconds_to_format((start_time - DateTime.current).ceil)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :clocks, dependent: :destroy

  # Validations ..................................
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { in: 6..20 }
end

app/controllers/app_controller.rb
# frozen_string_literal: true

# AppController
class AppController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# ApplicationController
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/clocks_controller.rb
class ClocksController < ApplicationController
  include ClocksHelper

  def index
    @clocks = current_user.clocks
  end

  def new
    @clock = current_user.clocks.new
  end

  def create
    @clock = current_user.clocks.new(clock_params)
    if @clock.save
      redirect_to clocks_path
    else
      render :index, notice: "Clock not created"
    end
  end

  private

  def clock_params
    params.require(:clock).permit(:description, :duration_time)
  end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clocks_helper.rb
module ClocksHelper
  def seconds_to_format(time)
    ClockService.seconds_to_format(time)
  end

  def format_to_seconds(time)
    ClockService.format_to_seconds(time)
  end
end

app/views/app/index.html.erb
<%= turbo_frame_tag :clocks, src: clocks_path, loading: 'lazy' %>

app/views/clocks/_form.html.erb
    <td>
      duration
    </td>

    <td>
      description
    </td>

app/views/clocks/index.html.erb
<%= turbo_frame_tag :clocks do %>
  <div class="container">
    <h1 class="mt-5">Clockwork</h1>
    <div class="row">
      <div class="col-md-12">
        <div class="alert alert-info">
          <p>Click on the "New clock" button to create a new clock.</p>
        </div>
      </div>
      <div class="col-md-12">
        <table class="table">
          <thead>
            <tr>
              <th>Duration</th>
              <th>Description</th>
              <th>Started at</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <%= form_with(model: Clock.new, local: true) do |f|%>
              <tr>
                <td><%= f.text_field :duration_time, class: 'form-control' %> </td>
                <td><%= f.text_field :description, class: 'form-control' %></td>
                <td><%= Time.now.strftime('%d/%m/%Y %H:%M:%S') %></td>
                <td>
                  <button type="submit" class="btn btn-sm btn-primary">
                    <i class="bi bi-plus"></i>
                  </button>
                </td>
              </tr>
            <% end %>
            <% @clocks.each do |clock| %>
              <tr>
                <td><%= seconds_to_format(clock.duration) %></td>
                <td><%= clock.description %></td>
                <td><%= clock.start_time.strftime('%d/%m/%Y %H:%M:%S') %></td>
                <td>
                  <%= link_to edit_clock_path(clock), class: 'btn btn-sm btn-success' do %>
                    <i class="bi bi-pencil"></i>
                  <% end %>
                  <%= button_to clock, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' do %>
                    <i class="bi bi-trash"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
        </table>
      </div>
    </div>
  </div>
<% end %>

app/views/clocks/new.html.erb
<%= turbo_frame_tag :new_clock do %>
  <%= render 'form', clock: @clock %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clockwork</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>